ARRANGE: COLUMN
ALIGN: MIDDLE
ORDER:
  - "!^DP-"
  - "!^eDP-1"
SCALE:
  - NAME_DESC: "eDP-1"
    SCALE: 1.75
MODE:
  - NAME_DESC: "eDP-1"
    WIDTH: 3200
    HEIGHT: 2000
    HZ: 60
LAPTOP_DISPLAY_PREFIX: "eDP-1"
