ARRANGE: ROW
ALIGN: MIDDLE
ORDER:
  - "!^eDP-1"
  - "!^DP-.*"
SCALE:
  - NAME_DESC: "California Institute of Technology 0x1626 0x00006002" # anuramat-ll7 internal
    SCALE: 2.25
  - NAME_DESC: "Dell Inc. DELL S2722QC 192SH24"
    SCALE: 1.75
MODE:
  - NAME_DESC: "California Institute of Technology 0x1626 0x00006002"
    WIDTH: 3200
    HEIGHT: 2000
    HZ: 165.001
  - NAME_DESC: "Dell Inc. DELL S2722QC 192SH24"
    WIDTH: 3840
    HEIGHT: 2160
    HZ: 59.997
LAPTOP_DISPLAY_PREFIX: "eDP-1"
