server_endpoint = "/run/user/1000/clipcat/grpc.sock"
finder = "custom_finder"

[custom_finder]
program = "tofi"
args = []

[log]
emit_journald = true
emit_stdout = false
emit_stderr = false
level = "INFO"
