#!/usr/bin/env bash

# requires curl

if command -v brew &> /dev/null
then
    echo "brew already installed"
    exit
fi

echo --------------------------------
echo --------------------------------
echo cfg: installing homebrew--------
echo --------------------------------
echo --------------------------------

NONINTERACTIVE=1 /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)" | tee -a .cfg.brew_install.log

echo --------------------------------
echo --------------------------------
echo cfg: installing packages--------
echo --------------------------------
echo --------------------------------

cat leaves.txt casks.txt | xargs brew install | tee -a .cfg.packages_install.log


