#!/usr/bin/env bash

# TODO run install_packages and install_dotfiles


# after install config stuff
conda config --set auto_activate_base false
# drag windows with ctrl+cmd+lmb anywhere
# defaults write -g NSWindowShouldDragOnGesture -bool true
