allow-missing-formatter = true
excludes = []
fail-on-change = true
walk = "git"
# possible values: <debug|info|warn|error|fatal>
on-unmatched = "debug"
# 0 = warn, 1 = info, 2 = debug
verbose = 0

[formatter.nix]
command = "nixfmt"
# cli args to command
options = []
# globs
includes = [ "*.nix" ]
excludes = []
priority = 0
