alpha = 80

[templates]
zathura = { src = 'zathura', target = "~/.config/zathura/generated-colors"}
foot = { src = 'foot', target = "~/.config/foot/generated-colors"}
mako = { src = 'mako', target = "~/.config/mako/generated-colors"}
