#!/usr/bin/env bash

[ "$1" = usage ] && {
	echo -e "\t$(basename "$0") "string to append" ITEM# [ITEM# ...]"
	echo -e '\t\tAppends a string to multiple tasks.'
	exit
}

text="$2"
shift 2

for tasknum in "$@"; do
	TODOTXT_VERBOSE=0 $TODO_SH command append "$tasknum" "$text"
done
