#!/usr/bin/env bash

[ "$1" = usage ] && {
	echo -e "\t$(basename "$0") [ITEM#]"
	echo -e '\t\tEdits the task interactively.'
	echo -e '\t\t(Last task when not specified)'
	exit
}

num=$("$XDG_CONFIG_HOME/todo/utils/linenr" "$2")

old=$(awk "NR == $num {print; exit}" "$TODO_FILE")
printf 'old: %s\n' "$old"
read -e -i "$old" -p 'new: ' -r new

[ "$new" = "$old" ] && echo "No changes" && exit 0

awk -v "new=$new" -- "NR == $num {sub(/.*/, new)}; {print}" "$TODO_FILE" | sponge "$TODO_FILE" && echo "Saved"
