#!/usr/bin/env bash
num=$2

[ "$1" = usage ] && {
	echo -e "\t$(basename "$0") [ITEM#]"
	echo -e '\t\tOpens the specified/last task for editing using GNU Readline.'
	exit
}

source "$TODO_ACTIONS_DIR/utils.sh"
num=$(linenr "$num")
linenr_handler

old=$(awk "NR == $num {print; exit}" "$TODO_FILE")
printf 'old: %s\n' "$old"
# standard IFS trims whitespace, empty -- preserves
read -e -i "$old" -p 'new: ' -r new

[ "$new" = "$old" ] || [[ $new =~ ^\s*$ ]] && {
	echo "No changes"
	exit 0
}

awk -v "new=$new" -- "NR == $num {sub(/.*/, new)}; {print}" "$TODO_FILE" | sponge "$TODO_FILE" && echo "Saved"
