#!/usr/bin/env bash

[ "$1" = usage ] && {
	echo '    edit ITEM#'
	echo '      Opens the line in $EDITOR.'
	exit
}
num=$2

# fallback to the last task
[ -z "$num" ] && {
	num=$(wc -l "$TODO_FILE" | cut -d ' ' -f 1)
}

# remove leading zeros
num=$((10#$num))

old=$(awk "NR == $num {print; exit}" "$TODO_FILE")
printf 'old: %s\n' "$old"
read -e -i "$old" -p 'new: ' -r new

[[ $new == $old ]] && echo "No changes" && exit 0

awk -v "new=$new" -- "NR == $num {sub(/.*/, new)}; {print}" "$TODO_FILE" | sponge "$TODO_FILE"
