#!/usr/bin/env bash
num=$2

[ "$1" = usage ] && {
	echo -e "\t$(basename "$0") [ITEM#]"
	echo -e '\t\tOpens the $TODO_FILE on the specified line in $EDITOR.'
	echo -e '\t\t(Last line when not specified)'
	exit
}

num=$("$XDG_CONFIG_HOME/todo/utils/linenr" "$num") || {
	echo oops
	exit 1
}

$EDITOR "+$num" "$TODO_FILE"
