#!/usr/bin/env bash
num=$2

[ "$1" = usage ] && {
	echo -e "\t$(basename "$0") [ITEM#]"
	echo -e '\t\tOpens the $TODO_FILE on the specified/last line using $EDITOR.'
	exit
}

source "$TODO_ACTIONS_DIR/utils.sh"
num=$(linenr "$num") || {
	echo "Invalid task number"
	exit 1
}

$EDITOR "+$num" "$TODO_FILE"
