#!/usr/bin/env bash

[ "$1" = usage ] && {
	echo -e '\topen [ITEM#]'
	echo -e '\t\tOpens the $TODO_FILE on the specified line in $EDITOR.'
	echo -e '\t\t(Last line when not specified)'
	exit
}

num=$("$XDG_CONFIG_HOME/todo/utils/linenr" "$2")

$EDITOR "+$num" "$TODO_FILE"
