local b = require('bindables')
local function norm(l, r, d)
  vim.keymap.set('n', l, r, { silent = true, desc = d })
end
norm('<leader>#', function()
  b.create_comment_header('~', nil, 120)
end, 'Create Comment Header')
norm('<leader>$', function()
  b.create_comment_header('~', nil, 60)
end, 'Create Comment Subheader')
