#!/usr/bin/env bash

# default layout
yabai -m config layout bsp

# padding
yabai -m config top_padding 0
yabai -m config bottom_padding 0
yabai -m config left_padding 0
yabai -m config right_padding 0
yabai -m config window_gap 0

# mouse
yabai -m config mouse_modifier fn
yabai -m config mouse_action1 move
yabai -m config mouse_action2 resize

# floating windows are always on top (default: off)
yabai -m config window_topmost on

# float system preferences
# TODO doesn't work for some reason yet
yabai -m rule --add title='System Settings' manage=off
yabai -m rule --add title='Preferences$' manage=off
# float settings windows
yabai -m rule --add title='Settings$' manage=off
