alias l="exa --group-directories-first --group --icons --header --git" 
alias v="nvim"
export EDITOR="nvim"
alias tree="exa --group-directories-first --group --icons --header --git --tree"
alias githehe="git add . && git commit -m \"hehe\" && git push"
